/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package csi;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;

/**
 * Interface grafica para exibir os Casos disponveis para o Jogador.
 * 
 * @author Murilo Ito, Janaina Cheim, Alexandre Jimenez e Patrick Guedes.
 */
public class CasosGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CasosGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelXP = new javax.swing.JLabel();
        labelEnergia = new javax.swing.JLabel();
        labelJogador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCasos = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        setName("Casos"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 34, 77));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 75));
        jLabel1.setForeground(new java.awt.Color(130, 149, 177));
        jLabel1.setText("CSI ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel2.setForeground(new java.awt.Color(120, 139, 168));
        jLabel2.setText("CASOS ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setForeground(new java.awt.Color(130, 149, 177));
        jLabel3.setText("JAVA 1ª TEMPORADA");

        labelXP.setFont(new java.awt.Font("Tahoma", 0, 12));
        labelXP.setForeground(new java.awt.Color(255, 51, 0));
        labelXP.setText("0");
        labelXP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "XP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(130, 149, 177))); // NOI18N

        labelEnergia.setFont(new java.awt.Font("Tahoma", 0, 14));
        labelEnergia.setForeground(new java.awt.Color(255, 51, 0));
        labelEnergia.setText("0");
        labelEnergia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENERGIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(130, 149, 177))); // NOI18N

        labelJogador.setForeground(new java.awt.Color(255, 51, 0));
        labelJogador.setText("Jogador: ");

        listCasos.setBackground(new java.awt.Color(120, 139, 168));
        listCasos.setForeground(new java.awt.Color(0, 0, 102));
        listCasos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listCasos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCasosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listCasos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelXP, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(labelJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelXP)
                    .addComponent(labelEnergia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelJogador)
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-650)/2, (screenSize.height-500)/2, 650, 500);
    }// </editor-fold>//GEN-END:initComponents

private void listCasosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCasosMouseClicked
    if ((evt.getClickCount() >= 2) && (listCasos.getSelectedIndex() >= 0)) {
        String caso = (String) listCasos.getModel().getElementAt( listCasos.getSelectedIndex() );
        String[] registro = caso.split("-");
        Controller.getController().carregaCaso( Integer.parseInt(registro[0].trim().substring(1)) );
    }
}//GEN-LAST:event_listCasosMouseClicked

    public void setEnergia(String energia) {
        labelEnergia.setText(energia);
    }
    
    public void setXP(String xp) {
        labelXP.setText(xp);
    }
    
    public void setJogador(String jogador) {
        labelJogador.setText(jogador);
    }
    
    public void setCasos(ArrayList<String> casos) {
        // limpa todos os possiveis itens antigos
        listCasos.removeAll();
        
        if (casos == null) return;
        
        DefaultListModel listModel = new DefaultListModel();  
        Iterator i = casos.iterator();
        
        while (i.hasNext()) {
            listModel.addElement((String) i.next());
        }
        
        listCasos.setModel(listModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEnergia;
    private javax.swing.JLabel labelJogador;
    private javax.swing.JLabel labelXP;
    private javax.swing.JList listCasos;
    // End of variables declaration//GEN-END:variables
}
