/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package csi;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;

/**
 * Interface grafica do laboratorio para processar as Pistas.
 * 
 * @author Murilo Ito, Janaina Cheim, Alexandre Jimenez e Patrick Guedes.
 */
public class LaboratorioGUI extends javax.swing.JFrame {

    /**
     * Creates new form LaboratorioGUI
     */
    public LaboratorioGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
/*
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPistas = new javax.swing.JList();
        buttonProcessar = new javax.swing.JButton();
        labelXP = new javax.swing.JLabel();
        labelEnergia = new javax.swing.JLabel();
        labelJogador = new javax.swing.JLabel();
        buttonLocais = new javax.swing.JButton();
        buttonCafe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 34, 77));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 75));
        jLabel1.setForeground(new java.awt.Color(130, 149, 177));
        jLabel1.setText("CSI ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel2.setForeground(new java.awt.Color(120, 139, 168));
        jLabel2.setText(" Pistas Encontradas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setForeground(new java.awt.Color(130, 149, 177));
        jLabel3.setText("JAVA 1ª TEMPORADA");

        listPistas.setBackground(new java.awt.Color(120, 139, 168));
        listPistas.setForeground(new java.awt.Color(0, 0, 102));
        listPistas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listPistas);

        buttonProcessar.setText("Processar Pistas");
        buttonProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcessarActionPerformed(evt);
            }
        });

        labelXP.setFont(new java.awt.Font("Tahoma", 0, 12));
        labelXP.setForeground(new java.awt.Color(255, 51, 0));
        labelXP.setText("0");
        labelXP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "XP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(130, 149, 177))); // NOI18N

        labelEnergia.setFont(new java.awt.Font("Tahoma", 0, 14));
        labelEnergia.setForeground(new java.awt.Color(255, 51, 0));
        labelEnergia.setText("0");
        labelEnergia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENERGIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(130, 149, 177))); // NOI18N

        labelJogador.setForeground(new java.awt.Color(255, 51, 0));
        labelJogador.setText("Jogador:");

        buttonLocais.setText("Locais");
        buttonLocais.setFocusPainted(false);
        buttonLocais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLocaisActionPerformed(evt);
            }
        });

        buttonCafe.setText("Beber Café");
        buttonCafe.setFocusPainted(false);
        buttonCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCafeActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(buttonCafe)
                        .add(18, 18, 18)
                        .add(buttonLocais)
                        .add(18, 18, 18)
                        .add(buttonProcessar))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 343, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel3)
                                .add(46, 46, 46)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(labelJogador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 204, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(labelXP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(18, 18, 18)
                                        .add(labelEnergia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(jScrollPane1))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labelXP)
                    .add(labelEnergia))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(labelJogador)
                .add(16, 16, 16)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(27, 27, 27)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buttonProcessar)
                    .add(buttonLocais)
                    .add(buttonCafe))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-666)/2, (screenSize.height-538)/2, 666, 538);
   */ }// </editor-fold>//GEN-END:initComponents

    private void buttonProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcessarActionPerformed
        Controller.getController().processarPistas();
    }//GEN-LAST:event_buttonProcessarActionPerformed
    
    private void buttonLocaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLocaisActionPerformed
        Controller.getController().mostraLocais(this);
    }//GEN-LAST:event_buttonLocaisActionPerformed
    
private void buttonCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCafeActionPerformed
    Controller.getController().beberCafe();
}//GEN-LAST:event_buttonCafeActionPerformed
    
    public void setEnergia(String energia) {
        labelEnergia.setText(energia);
    }
    
    public void setXP(String xp) {
        labelXP.setText(xp);
    }
    
    public void setJogador(String jogador) {
        labelJogador.setText(jogador);
    }
    
    public void setPistas(ArrayList<String> pistas) {
        // limpa todos os possiveis itens antigos
        listPistas.removeAll();
        
        if (pistas == null) return;
        
        DefaultListModel listModel = new DefaultListModel();  
        Iterator i = pistas.iterator();
        
        while (i.hasNext()) {
            listModel.addElement((String) i.next());
        }
        
        listPistas.setModel(listModel);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCafe;
    private javax.swing.JButton buttonLocais;
    private javax.swing.JButton buttonProcessar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEnergia;
    private javax.swing.JLabel labelJogador;
    private javax.swing.JLabel labelXP;
    private javax.swing.JList listPistas;
    // End of variables declaration//GEN-END:variables
}
