/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package csi;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 * Interface gráfica par exibir um Local.
 * 
 * @author Murilo Ito, Janaina Cheim, Alexandre Jimenez e Patrick Guedes.
 */
public class LocalGUI extends javax.swing.JFrame {

    /**
     * Creates new form LocalGUI
     */
    public LocalGUI() {
        //initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
}
