/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package csi;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 * Interface gráfica par exibir um Local.
 * 
 * @author Murilo Ito, Janaina Cheim, Alexandre Jimenez e Patrick Guedes.
 */
public class LocalGUI extends javax.swing.JFrame {

    /**
     * Creates new form LocalGUI
     */
    public LocalGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
/*
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelLocal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelXP = new javax.swing.JLabel();
        labelEnergia = new javax.swing.JLabel();
        buttonPista2 = new javax.swing.JButton();
        buttonPista1 = new javax.swing.JButton();
        buttonPista4 = new javax.swing.JButton();
        buttonLocais = new javax.swing.JButton();
        buttonPista3 = new javax.swing.JButton();
        labelJogador = new javax.swing.JLabel();
        buttonLab = new javax.swing.JButton();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bt_jogar.gif"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(182, 25, 28), 1, true));
        jButton1.setMaximumSize(new java.awt.Dimension(75, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(75, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(75, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Player: ABCG");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 34, 77));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 75)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(130, 149, 177));
        jLabel1.setText("CSI ");

        labelLocal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelLocal.setForeground(new java.awt.Color(120, 139, 168));
        labelLocal.setText("Local do Crime: Procurar Pistas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(130, 149, 177));
        jLabel3.setText("JAVA 1ª TEMPORADA");

        labelXP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelXP.setForeground(new java.awt.Color(255, 51, 0));
        labelXP.setText("0");
        labelXP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "XP", 0, 0, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(130, 149, 177))); // NOI18N

        labelEnergia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEnergia.setForeground(new java.awt.Color(255, 51, 0));
        labelEnergia.setText("0");
        labelEnergia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENERGIA", 0, 0, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(130, 149, 177))); // NOI18N

        buttonPista2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pista.gif"))); // NOI18N
        buttonPista2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 25, 28)));
        buttonPista2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pista_hover.gif"))); // NOI18N
        buttonPista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPista2ActionPerformed(evt);
            }
        });

        buttonPista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pista.gif"))); // NOI18N
        buttonPista1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 25, 28)));
        buttonPista1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pista_hover.gif"))); // NOI18N
        buttonPista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPista1ActionPerformed(evt);
            }
        });

        buttonPista4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pista.gif"))); // NOI18N
        buttonPista4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 25, 28)));
        buttonPista4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pista_hover.gif"))); // NOI18N
        buttonPista4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPista4ActionPerformed(evt);
            }
        });

        buttonLocais.setText("Locais");
        buttonLocais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLocaisActionPerformed(evt);
            }
        });

        buttonPista3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pista.gif"))); // NOI18N
        buttonPista3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 25, 28)));
        buttonPista3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pista_hover.gif"))); // NOI18N
        buttonPista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPista3ActionPerformed(evt);
            }
        });

        labelJogador.setForeground(new java.awt.Color(255, 51, 0));
        labelJogador.setText("Jogador:");

        buttonLab.setText("Laboratório");
        buttonLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLabActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(40, 40, 40)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(36, 36, 36)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(labelXP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(labelEnergia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(labelJogador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 204, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, labelLocal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(buttonLab)
                                .add(18, 18, 18)
                                .add(buttonLocais))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(buttonPista1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(buttonPista2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(33, 33, 33)
                                .add(buttonPista3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(31, 31, 31)
                                .add(buttonPista4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(11, 11, 11)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labelXP)
                    .add(labelEnergia))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(labelJogador)
                .add(18, 18, 18)
                .add(labelLocal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(27, 27, 27)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buttonPista2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buttonPista4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buttonPista3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buttonPista1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(33, 33, 33)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buttonLocais)
                    .add(buttonLab))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-650)/2, (screenSize.height-500)/2, 650, 500);
*/    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonLocaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLocaisActionPerformed
        Controller.getController().mostraLocais(this);
    }//GEN-LAST:event_buttonLocaisActionPerformed

    private void buttonPista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPista1ActionPerformed
        procurouPista(buttonPista1.getText());
    }//GEN-LAST:event_buttonPista1ActionPerformed

private void buttonLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLabActionPerformed
    Controller.getController().visitaLaboratorio(this);
}//GEN-LAST:event_buttonLabActionPerformed

private void buttonPista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPista2ActionPerformed
    procurouPista(buttonPista2.getText());
}//GEN-LAST:event_buttonPista2ActionPerformed

private void buttonPista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPista3ActionPerformed
    procurouPista(buttonPista3.getText());
}//GEN-LAST:event_buttonPista3ActionPerformed

private void buttonPista4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPista4ActionPerformed
    procurouPista(buttonPista4.getText());
}//GEN-LAST:event_buttonPista4ActionPerformed

    public void setEnergia(String energia) {
        labelEnergia.setText(energia);
    }

    public void setXP(String xp) {
        labelXP.setText(xp);
    }

    public void setJogador(String jogador) {
        labelJogador.setText(jogador);
    }
    
    public void setLocal(String local) {
        labelLocal.setText("Local do Crime: " + local);
    }
    
    public void setPistas(ArrayList<Pista> pistas) {
        
        ArrayList<javax.swing.JButton> botoes = new ArrayList<javax.swing.JButton>();
        botoes.add(buttonPista1);
        botoes.add(buttonPista2);
        botoes.add(buttonPista3);
        botoes.add(buttonPista4);
        
        // randomiza a ordem dos botoes
        botoes = shuffleArrayList(botoes);
        
        Iterator iBt = botoes.iterator();
        Iterator iPistas = pistas.iterator();
        
        javax.swing.JButton botao;
        Pista pista;
        
        // coloca as pistas nos botoes
        while (iBt.hasNext()) {
            botao = (javax.swing.JButton) iBt.next();
            
            if (iPistas.hasNext()) {
                pista = (Pista) iPistas.next();
                botao.setText( Integer.toString(pista.getId()) );
            } else {
                botao.setText("");
            }
        }
        
    }
    
    private void procurouPista(String id) {
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nada encontrado");
            return;
        }
        
        Controller.getController().achouPista(Integer.parseInt(id));
    }
    
    private ArrayList shuffleArrayList(ArrayList source) {
        ArrayList sortedList = new ArrayList();
        Random generator = new Random();

        while (source.size() > 0) {
            int position = generator.nextInt(source.size());
            sortedList.add(source.get(position));
            source.remove(position);
        }

        return sortedList;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLab;
    private javax.swing.JButton buttonLocais;
    private javax.swing.JButton buttonPista1;
    private javax.swing.JButton buttonPista2;
    private javax.swing.JButton buttonPista3;
    private javax.swing.JButton buttonPista4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelEnergia;
    private javax.swing.JLabel labelJogador;
    private javax.swing.JLabel labelLocal;
    private javax.swing.JLabel labelXP;
    // End of variables declaration//GEN-END:variables
}
