/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package csi;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * Interface grafica para exibir os locais de um Caso.
 * 
 * @author Murilo Ito, Janaina Cheim, Alexandre Jimenez e Patrick Guedes.
 */
public class LocaisGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public LocaisGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelXP = new javax.swing.JLabel();
        labelEnergia = new javax.swing.JLabel();
        buttonLab = new javax.swing.JButton();
        labelJogador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listLocais = new javax.swing.JList();
        labelCaso = new javax.swing.JLabel();
        labelDescricao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 34, 77));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 75));
        jLabel1.setForeground(new java.awt.Color(130, 149, 177));
        jLabel1.setText("CSI ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(120, 139, 168));
        jLabel2.setText("LOCAIS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setForeground(new java.awt.Color(130, 149, 177));
        jLabel3.setText("JAVA 1ª TEMPORADA");

        labelXP.setFont(new java.awt.Font("Tahoma", 0, 12));
        labelXP.setForeground(new java.awt.Color(255, 51, 0));
        labelXP.setText("0");
        labelXP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "XP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(130, 149, 177))); // NOI18N

        labelEnergia.setFont(new java.awt.Font("Tahoma", 0, 14));
        labelEnergia.setForeground(new java.awt.Color(255, 51, 0));
        labelEnergia.setText("0");
        labelEnergia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENERGIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(130, 149, 177))); // NOI18N

        buttonLab.setText("Laboratório");
        buttonLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLabActionPerformed(evt);
            }
        });

        labelJogador.setForeground(new java.awt.Color(255, 51, 0));
        labelJogador.setText("Jogador: ");

        listLocais.setBackground(new java.awt.Color(120, 139, 168));
        listLocais.setForeground(new java.awt.Color(0, 0, 102));
        listLocais.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listLocais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listLocaisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listLocais);

        labelCaso.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelCaso.setForeground(new java.awt.Color(120, 139, 168));
        labelCaso.setText("CASO:");

        labelDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDescricao.setForeground(new java.awt.Color(212, 223, 255));
        labelDescricao.setText("Descrição:");
        labelDescricao.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelXP, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelCaso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonLab)
                                .addComponent(labelJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)))
                        .addContainerGap(75, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelXP)
                    .addComponent(labelEnergia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelJogador)
                .addGap(10, 10, 10)
                .addComponent(labelCaso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonLab)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-650)/2, (screenSize.height-500)/2, 650, 500);
    }// </editor-fold>//GEN-END:initComponents

private void buttonLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLabActionPerformed
    Controller.getController().visitaLaboratorio(this);
}//GEN-LAST:event_buttonLabActionPerformed

private void listLocaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listLocaisMouseClicked
    if ((evt.getClickCount() >= 2) && (listLocais.getSelectedIndex() >= 0)) {
        Local local = (Local) listLocais.getModel().getElementAt( listLocais.getSelectedIndex() );
        Controller.getController().visitaLocal(local.getId());
    }
}//GEN-LAST:event_listLocaisMouseClicked

    public void setEnergia(String energia) {
        labelEnergia.setText(energia);
    }

    public void setXP(String xp) {
        labelXP.setText(xp);
    }

    public void setJogador(String jogador) {
        labelJogador.setText(jogador);
    }
    
    public void setCaso(String caso) {
        labelCaso.setText("CASO: " + caso);
    }
    
    public void setDescricao(String desc) {
        labelDescricao.setText("Descrição: " + desc);
    }
    
    public void setLocais(ArrayList<Local> locais) {
        // limpa todos os possiveis itens antigos
        listLocais.removeAll();
        
        if (locais == null) return;
        
        DefaultListModel listModel = new DefaultListModel();  
        Iterator i = locais.iterator();
        
        while (i.hasNext()) {
            listModel.addElement((Local) i.next());
        }
        
        listLocais.setModel(listModel);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCaso;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelEnergia;
    private javax.swing.JLabel labelJogador;
    private javax.swing.JLabel labelXP;
    private javax.swing.JList listLocais;
    // End of variables declaration//GEN-END:variables
}
